# Generated by Django 4.2.10 on 2026-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.TextField()),
                ('carbrand', models.TextField()),
                ('carmodel', models.TextField()),
                ('carprice', models.TextField()),
            ],
            options={
                'db_table': 'api_car',
            },
        ),
    ]
